[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect all API calls to Railway backend
[[redirects]]
  from = "/api/*"
  to = "https://inboxfolio-production.up.railway.app/api/:splat"
  status = 200
  force = true

# SPA fallback for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://inboxfolio-production.up.railway.app/api"

[context.deploy-preview.environment]
  VITE_API_URL = "https://inboxfolio-production.up.railway.app/api"

[context.branch-deploy.environment]
  VITE_API_URL = "https://inboxfolio-production.up.railway.app/api"